[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "automas_plugin_mumu_adapter"
version = "0.0.1"
description = """<!--{"zh_CN":"MuMu 模拟器游戏适配","en":"MuMu emulator game adapter"}-->"""
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.12"
keywords = [
  """<!--{"zh_CN":["游戏","模拟器","MuMu"],"en":["game","emulator","mumu"]}-->""",
  "auto-mas-plugin",
  "auto-mas-id:mumu_adapter",
]
dependencies = ["auto_mas_core>=6,<7"]

[project.urls]
auto-mas-display-name = """<!--{"zh_CN":"MuMu 适配","en":"MuMu Adapter"}-->"""

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
mumu_adapter = ["i18n/*.json"]
